name: called
on:
  workflow_call:
    inputs:
      x:
        type: boolean

jobs:
  check-alpha:
    runs-on: ubuntu-latest
    outputs:
      is_alpha: ${{ steps.check_alpha.outputs.match }}

    steps:
      - 
        name: Check alpha
        id: check_alpha
        run: |
          if [[ "Deploy alpha [staging 1.0.0]" =~ \[staging[[:space:]]v?[0-9].[0-9].[0-9]\] ]]; then
              echo alpha
              echo "match=true" >> $GITHUB_OUTPUT
          fi
  test2:
    runs-on: ubuntu-latest
    needs: check-alpha
    if: ${{ needs.check-alpha.outputs.is_alpha == 'true' }}
    steps:
      -
        name: test
        run: echo result is ${{ needs.test1.outputs.is_alpha }}
